---
undesired_services:
  - upower
  - wpa_supplicant

undesired_packages:
  - tracker-extract

required_packages:
  - gawk
  - python3-psutil
  - raspi-utils-core
  - sed
  - wakeonlan

pihole_rev_server_domain: "picapsule.local"
pihole_rev_server_target: "192.168.1.115"
pihole_rev_server_cidr: "192.168.1.0/24"
pihole_dnssec_enabled: "true"
pihole_dnsmasq_listening: "local" # local/all
pihole_privacy_level: "0" # 0 = Show everything, 1 = Hide domains and clients, 2 = Hide domains, 3 = Hide everything
pihole_local_cname_records: |
  cname=pihole.picapsule.local, picapsule.local
pihole_local_dns_records: |
  192.168.1.115 picapsule.local
  192.168.1.174 homebridge.local

# TimeCapsule configuration
timecapsule_user: "picapsule"
timecapsule_disk_name: "picapsule1"

# DNSCrypt configuration
dnscrypt_arch: { archive: linux_arm, dir: linux-arm }
dnscrypt_on_pihole: "true"
dnscrypt_sysd_socket_only: false
# dnscrypt_bin: /opt/dnscrypt-proxy/dnscrypt-proxy
# dnscrypt_config: /opt/dnscrypt-proxy/dnscrypt-proxy.toml
dnscrypt_server_names: ['quad9-dnscrypt-ip4-filter-ecs-pri', 'quad9-dnscrypt-ip4-filter-pri', 'dnscry.pt-amsterdam02-ipv4', 'dnscry.pt-anon-copenhagen-ipv4']
dnscrypt_anonymizer_server_names: ['anon-scaleway-ams', 'anon-sth-se', 'anon-v.dnscrypt.uk-ipv4,dnscry.pt-anon-madrid-ipv4', 'dnscry.pt-anon-munich-ipv4']
dnscrypt_port: 5055
dnscrypt_doh_servers: "false"
dnscrypt_require_dnssec: "true"
dnscrypt_require_nolog: "true"
dnscrypt_require_nofilter: "false"
dnscrypt_force_tcp: "true"
dnscrypt_lb_strategy: "'p2'"
dnscrypt_lb_estimator: "true"
dnscrypt_bootstrap_resolvers: ['9.9.9.9:53', '8.8.8.8:53']
dnscrypt_ignore_system_dns: "true"
dnscrypt_netprobe_timeout: 60
dnscrypt_netprobe_address: '9.9.9.9:53'
dnscrypt_cache_size: 4096
dnscrypt_cache_min_ttl: 2400
dnscrypt_timeout: 5000

# Cloudflared configuration
cloudflared_use_enviorment_file: false
cloudflared_upstream_dns:
  - https://doh.la.ahadns.net/dns-query
  - https://dns.digitale-gesellschaft.ch/dns-query
cloudflared_no_autoupdate: false
cloudflared_service_name: "cloudflared-proxy.service"
cloudflared_service_file: "/etc/systemd/system/cloudflared-proxy.service"
