---
- name: Check current swap size
  ansible.builtin.command: grep '^CONF_SWAPSIZE=' /etc/dphys-swapfile
  register: current_swap_size
  changed_when: false
  failed_when: false

- name: Increase swap size to 512MB if not already set
  ansible.builtin.lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE=512'
  when: current_swap_size.stdout != 'CONF_SWAPSIZE=512'
  register: swapfile_config
  notify: Restart dphys-swapfile
